### ISSUE TITLE
WINDOWS BINARIES?

### ISSUE THREAD

**Issue by kokolino2** [xhlove/XstreamDL-CLI#1]
Hello, 'xhlove'!

Would you mind, creating Windows binaries, occasionally (and also working, on Windows XP, 64 bit, system/PC, if possible)?

Thus I can actively test your programme, because I often play different live streams (like "AES-128" encrypted,  and "SAMPLE-AES" encrypted, too)!?

Good luck!!!!!

Peter

**Comment by xhlove** [comment]
v1.0.0 released now !

**Comment by kokolino2** [comment]
THANK You, VERY MUCH!!!!! I will test/try it, very soon!!!! And I will post here the result!!!!! THANK You, again!!!!!!!

**Comment by kokolino2** [comment]
I still can not make it working (for me)! But I will go on with trying!!!

**Comment by xhlove** [comment]
post your error info here.
