### ISSUE TITLE
can't download ism

### ISSUE THREAD

**Issue by m0ck69** [xhlove/XstreamDL-CLI#11]
I cannot download ism url.
Example
`https://r.cdn-ncplus.pl/vod/store01/NOV_R4OYTzmruX3PKLRHkTAu/_/hd4-hssdrm02.ism/manifest`

**Comment by xhlove** [comment]
bug fixed https://github.com/xhlove/XstreamDL-CLI/commit/574b51f9654b1546a7c45f2ae0faf35872d305a6

![image](https://user-images.githubusercontent.com/48152166/127759496-af537e74-e60f-4ca3-a3fb-0785676f67ed.png)

**Comment by m0ck69** [comment]
Can you update exe?
I hope that the spped is good.
yt-dlp also works with ism but it downloads such files extremely slow.
I really hope that you downloader is fast.

**Comment by xhlove** [comment]
updated~

https://github.com/xhlove/XstreamDL-CLI/releases/tag/1.2.6

**Comment by m0ck69** [comment]
One more question If I may.
How do I download best video and audio by default? Is there a parameter like -best or sth like that?

**Comment by xhlove** [comment]
haven't implement, next version will be

**Comment by m0ck69** [comment]
OK. I'll be waiting. Thx.

**Comment by m0ck69** [comment]
I'm sorry to bother again but it doesn't work for me.
I want to download stream 5 (720p) of this  `https://r.cdn-ncplus.pl/vod/store01/NOV_R4OYTzmruX3PKLRHkTAu/_/hd4-hssdrm02.ism/manifest` but the output video has only 400 kb and it should be approx 800 mb.
My command line:
`XstreamDL-CLI_v1.2.6  --raw-concat --select https://r.cdn-ncplus.pl/vod/store01/NOV_R4OYTzmruX3PKLRHkTAu/_/hd4-hssdrm02.ism/manifest`

**Comment by xhlove** [comment]
It shows that the link to video segment it 404 now...

you should check its segment link from browser

if not 404, plz post one segment link here

**Comment by m0ck69** [comment]
I checked with different link and it's the same
`https://r.cdn-ncplus.pl/vod/store01/NOV_M4MbGdP3qn48v8lL3IVU/_/hd4-hssdrm02.ism/manifest`
https://user-images.githubusercontent.com/46628545/127762277-4f8495f5-9aa4-4351-a32f-977d55953159.mp4

**Comment by xhlove** [comment]
I means that you should open the online video page where the ism link comes form, and then F12 to open developer tool, and find the signle video segment link. NOT just test XstreamDL-CLI to download...

**Comment by m0ck69** [comment]
manifest
`https://r.cdn-ncplus.pl/vod/store01/NOV_M4MbGdP3qn48v8lL3IVU/_/hd4-hssdrm02.ism/manifest`

fragment
`https://ec01-ktw2.waw5.cache.orange.pl/canal/v/canal/vod/store01/NOV_M4MbGdP3qn48v8lL3IVU/_/hd4-hssdrm02.ism/QualityLevels(125435)/Fragments(Polski=20053333)`

The above is from canalplus site. Their videos don't have init files. Maybe that is the reason?

**Comment by xhlove** [comment]
its a 302 problem, has been fixed, release of v1.2.6 has updated, download the new version of v1.2.6

**Comment by m0ck69** [comment]
Now it works. The file is downloaded fast!

Normally it use yt-dlp to download manifest ism.
I get ismv and isma files. Then I generate init files, mux them into ismv and isma and then decrypt.
XstreamDL-CLI gives me mp4 file (not ism) and I don't know why but it's easier to mux init files now.

**Comment by xhlove** [comment]
what is the online page of this manifest

**Comment by m0ck69** [comment]
I'll contact you on discord.

**Comment by ImVantexHD** [comment]
> Now it works. The file is downloaded fast!
> 
> Normally it use yt-dlp to download manifest ism.
> I get ismv and isma files. Then I generate init files, mux them into ismv and isma and then decrypt.
> XstreamDL-CLI gives me mp4 file (not ism) and to mux init files I jeed to know track ID but mediainfo does not show track id for raw files.
> 

Hi, i'm curious about your method to generate the init files for "ismv/isma", at the moment i know one overcomplicated method by going on this [site](http://reference.dashif.org/dash.js/v3.2.1/samples/dash-if-reference-player) and manipulate the JavaScript in the network tab which will output the init in base64 that i can decode [here](https://base64.guru/converter/decode/file)

But this seems to work only for video and not for audio, i usually download all the segments with XstreamDL-CLI for encrypted tracks and then combine all the segments with the init file using `copy /b *mp4 out.mp4` then decrypt with mp4decrypt which is working fine. (only for the video part)

here's an example for HBO GO: (im not sure about the other sites but with this one the audio part won't work whatever i do)
https://edgecastcdnsecure.hbogo.eu/2bc97f35-3eee-d3b4-b4ec-31c9b0ea3e04_hbo/COMP/21269794_rom_comp_8d38dbc6-382e-45ec-b68a-ca8d8cd65bb7_3400000_v2.ism/manifest
audio init: [audio_ron_st_ori](http://public.vantex.workers.dev/1:/init.mp4)
mp4decrypt --key 192d3c8d2b621294055719a6be82af27:3465fb989e08ac8ff4213120b88d0370 0.mp4 1.mp4

if you're willing to help me out contact me on discord Vantex#9686 or telegram https://t.me/vantexhd

**Comment by m0ck69** [comment]
@ImVantexHD I use exactly the same method.
Audio: https://www24.zippyshare.com/v/H4zK6HRs/file.html

**Comment by ImVantexHD** [comment]
> @ImVantexHD I use exactly the same method.
> Audio: https://www24.zippyshare.com/v/H4zK6HRs/file.html

well, this is really strange in fact the audio that you sent is working, but for me after i got to the decryption part and the file is unplayable, have you tried exactly the same init and the decryption key that i posted above or did you change something?
Also are you using the latest version of mp4decrypt from [Bento4](https://www.bok.net/Bento4/binaries/Bento4-SDK-1-6-0-639.x86_64-microsoft-win32.zip) or maybe a modded one?

this is what i got in the end: [encrypted](http://public.vantex.workers.dev/1:/encrypted.mp4) can you decrypt this?
i made sure that i put the init at the top when i muxed them with the rest segments, not sure if that's a problem but whatever...
