### ISSUE TITLE
No track ID - problem

### ISSUE THREAD

**Issue by m0ck69** [xhlove/XstreamDL-CLI#12]
Hi.
I have a question.

I downloaded the same manifest file using yt-dlp and XstreamDL.
XstreamDL is much faster and I like this app more.
However, the output files are different.

yt-dlp gives video.ismv and XstreamDL video.mp4

![mediainfo](https://user-images.githubusercontent.com/46628545/127817751-06125aeb-32f7-4dfc-b91f-519892022d18.jpg)

The problem is that both videos cannot be decrypted because they don't have init files.
I can get init files but to mux them I need to know video track ID.
In this case it is 9. But video downloaded by XstreamDL doesn't show any information.

Can you explain it, please?

**Comment by xhlove** [comment]
Because I dont know how to deal with it, just do a binary merage for downloaded contents.

**Comment by m0ck69** [comment]
How to do binary merge?

**Comment by xhlove** [comment]
your image "video1.mp4" is a binary merge output

**Comment by m0ck69** [comment]
OK. It's strange because even mp4info from bento4 doesn't show any information.
Anyway, thanks for the replay.

I'm waiting for the next update with `best `option.
btw, I even when I use `--name` for instane `--name my video` the output name looks something like that `my video H264_1280x720_2499.97kbps`. I think it should be just `my video.`

**Comment by xhlove** [comment]
1. track ID problem may has benn fixed, plz test latest python scripts
2. `--name` option mean output filename prefix, when you download with multi stream for one ism/mpd, we must specific unique output name. So, I add bitrate, codec and resolution to make them wont be same filename
3. best option will not implement recent version
