### ISSUE TITLE
can't download mpd

### ISSUE THREAD

**Issue by m0ck69** [xhlove/XstreamDL-CLI#13]
Hello.
Xstream can't download such mpd

`https://ads-cdn-dash-1.blim.com/v1/dash/942b5dcb4f33f2d7bcfe75473f6d9bed3d3d2ff0/avod_prod_ts/201712054084/dash/671210_46e6ebdf0aabd6dcfcaf6bcf7dc4fa14/mpds/671210.mpd`

**Comment by xhlove** [comment]
DO NOT PASTE mpd url ONLY.

Check following:

1. What is the correct segment url in your brower ?
2. What is the segment url request headers in your brower ?
3. Does it has any ip location restriction ?

**Comment by xhlove** [comment]
bug fixed in v1.2.8

https://github.com/xhlove/XstreamDL-CLI/releases/tag/1.2.8

**Comment by rexioni** [comment]
Could you help me with a widevine header please.
url: https://ads-cdn-dash-1.blim.com/v1/dash/942b5dcb4f33f2d7bcfe75473f6d9bed3d3d2ff0/avod_prod_ts/201205181722/dash/446259_098169df1399463664e02f213470e334/mpds/446259.mpd
Widevine Url: https://api.blim.com/license/widevine
Custom Name: authorization
Custom Value: OAuth oauth_consumer_key="36c26d5ec5921c7c2199f8d107946be26a0a49865144724c42b5be0e4d133570", oauth_nonce="YKcYFI", oauth_signature="7pQ%2BDGJYn0Ta1Rz%2FQt5ZhjAwtL0%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1636375118", oauth_version="1.0"
code:
`authorization: OAuth oauth_consumer_key="36c26d5ec5921c7c2199f8d107946be26a0a49865144724c42b5be0e4d133570", oauth_nonce="YKcYFI", oauth_signature="7pQ%2BDGJYn0Ta1Rz%2FQt5ZhjAwtL0%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1636375118", oauth_version="1.0"`
