### ISSUE TITLE
ver 1.2.8 do not merge ism

### ISSUE THREAD

**Issue by m0ck69** [xhlove/XstreamDL-CLI#14]
Hi.
New version 1.2.8 do not merge ism although I use` --raw-concat`
Why?
![Clipboard01](https://user-images.githubusercontent.com/46628545/128590516-2163cd12-adc6-4d0b-a5b7-69f405fefad2.jpg)

**Comment by xhlove** [comment]
from this issue https://github.com/xhlove/XstreamDL-CLI/issues/11

I guess the way you to decrypt is one by one, so I cancel --raw-concat for encrypted ism

**Comment by xhlove** [comment]
Or there are some people to ask me why XstreamDL-CLI do not decrypt it only do a useless binary merge

**Comment by m0ck69** [comment]
No, no , no.
I need merged file to decrypt. Please add --raw-concat again.

**Comment by m0ck69** [comment]
@xhlove You can have --disable-auto-concat by default with encrypted ism BUT when I use --raw-concat I want files to be merged.

**Comment by xhlove** [comment]
try v1.2.9

**Comment by ImVantexHD** [comment]
@m0ck69 can you check my last comment on issue #11?
i still haven't figured why the audio track won't work even though i'm following the same method as for video which is playing fine

**Comment by m0ck69** [comment]
@xhlove I just tested it and it's working excellent. Thank you very much.
@ImVantexHD It doesn't work for you because audio ID and init audio ID are different. You must change init ID accordingly to the audio.

**Comment by ImVantexHD** [comment]
@m0ck69 i spent 1 hour to figure out this shit with no result, this is what i tried:
1. Downloading all the segments with XstreamDL_CLI
2. I changed the init ID using `MP4Box -set-track-id 2:1 init.mp4` to match the audio ID which is 1
3. Merging all the segments with the edited init
4. Decrypt the result with mp4decrypt

and this is what i got: [decrypted](http://public.vantex.workers.dev/1:/decrypted.mp4)  (no, is not playing at all)
did i miss something?
