### ISSUE TITLE
大佬我是隔壁帖子的用了你的软件解析出来了 但是解密没成功

### ISSUE THREAD

**Issue by chali26** [xhlove/XstreamDL-CLI#19]
[
![image](https://user-images.githubusercontent.com/73935991/134768181-5e1b5417-587d-4d90-952a-54e3cb0a7580.png)
![image](https://user-images.githubusercontent.com/73935991/134768197-04c08a19-36bd-4194-b0dc-e41764329587.png)
](url)
我用了你的软件解析出来了视频和音频 然后我用MP4decrypt解密没成功 我解析出来的视频和音频对吗 应该怎么解密啊 求大佬帮助 （因为我不太懂代码 安装过程也是很糊涂 可能操作的也不对）

**Comment by xhlove** [comment]
把mp4decrypt.exe放软件同一个目录，然后你在命令行加一个命令，下载后会自动解密的

--key 9f5872906bb14b478b1a43a0a11441ae:594f9b4ac5d0cddb05f09c86dcf3d910

**Comment by chali26** [comment]
[
![image](https://user-images.githubusercontent.com/73935991/134769506-ee1b2390-0cda-40bb-a08c-2d255c441216.png)
![image](https://user-images.githubusercontent.com/73935991/134769520-1fa44a35-45fd-48d6-aab4-d4a1caf4be8d.png)
](url)
没解成功。。。这个--key 9f5872906bb14b478b1a43a0a11441ae:594f9b4ac5d0cddb05f09c86dcf3d910 要放在什么位置啊 我是用的cmd直接输入的没有用py

**Comment by xhlove** [comment]
Downloads文件夹下面的文件呢，你也没截图

**Comment by chali26** [comment]
[
![image](https://user-images.githubusercontent.com/73935991/134771472-df7819bc-4bc0-462a-b314-93bb678e3105.png)
![image](https://user-images.githubusercontent.com/73935991/134771480-5f821994-700e-4f24-9b07-88a7b2f11140.png)
](url)
我不会解了 大佬说一下应该怎么解密吧

**Comment by xhlove** [comment]
有decrypted的就是解密好的啊。

**Comment by chali26** [comment]
可以了大佬 我刚开始是直接双击点开的 然后说看不了 我以为没解密成功呢后来我用potplayer打开就可以看了 谢谢大佬耐心的解答了 非常感谢 最后想问一下 是不是这个软件输入mpd之后里面的所有清晰度都直接下载啊 因为我这个音视频一共有7个 他没有选项直接全给我下载下来了

**Comment by xhlove** [comment]
有GUI，你可以使用GUI调用下载，这个是命令行软件，你可以去了解一下命令行软件怎么使用，或者翻一翻readme和issue，有一些命令示例

**Comment by chali26** [comment]
我自己在研究研究 谢谢大佬
