### ISSUE TITLE
请问大佬优酷、爱奇艺、腾讯视频超前点播可以下载吗

### ISSUE THREAD

**Issue by sunny111120** [xhlove/XstreamDL-CLI#2]
请问大佬优酷、爱奇艺、腾讯视频超前点播可以下载吗

**Comment by daofeng2015** [comment]
> 请问大佬优酷、爱奇艺、腾讯视频超前点播可以下载吗

超前点播都有drm保护的,你需要解开才能下

**Comment by xhlove** [comment]
下载是可以的，但是不能解密

**Comment by mayuyuismywife** [comment]
国内三大平台的超前点播使用的DRM情况都不一样，腾讯视频以及爱奇艺非独播剧集DRM系统是用Widevine L3加密，爱奇艺的独播剧集DRM系统是用Marlin BBTS，优酷是部分用Widevine L3，另一部分用自己研的DRM系统copyrightDRM

**Comment by xhlove** [comment]
已知key的情况下，现在可以命令行传递key（widevine&标准aes-cbc-128），实现下载后自动解密

**Comment by wanbangshucheng** [comment]
我想知道我如何获取优酷密钥？可以给个插件或者脚本吗
