### ISSUE TITLE
大大 能帮我看一下 像这种mpd为什么下不了吗

### ISSUE THREAD

**Issue by huliad2022** [xhlove/XstreamDL-CLI#24]
https://manifest.prod.boltdns.net/manifest/v1/dash/live-baseurl/bccenc/6182597161001/43760353-82c2-4dbe-9b42-e1f5ecd90157/6s/manifest.mpd?behavior_id=309ea3f0-8cb4-4b2a-b93a-0a2207360930&fastly_token=NjE2ZTAwYThfMjdhNmJjYTk5NjlhMmI5YWY5NmRhYTVkZThmOTM2N2Q5NjgwNTJhMDcxNTNkMWNiN2JjNTMwOGRjMWJmMDRiNQ%3D%3D

![搜狗截图20211019002356](https://user-images.githubusercontent.com/77323405/137770732-6508ca77-b0e5-47a4-8b22-f0c0feac113b.png)
一直是这样~

**Comment by xhlove** [comment]
--prefer-content-base-url

**Comment by xhlove** [comment]
那是另一个选项

我写的是

--prefer-content-base-url

看下readme

**Comment by daliali2088** [comment]
看到了 是不是只能用python命令执行下载 
用gui的话是不是就不行
