### ISSUE TITLE
Downloading from Disney plus fails

### ISSUE THREAD

**Issue by Essam23** [xhlove/XstreamDL-CLI#25]
Hi, When i try to download from Disney plus the downloading fails and I get this error message, you could test with this link.

https://vod-ftc-na-west-1.media.dssott.com/ps01/disney/f657fa6f-c2bc-4145-96ce-f7f8c4cb023d/ctr-all-1f4d434d-c9bc-48bc-9deb-a4cfbe4e4b2f-dd4beaa9-76b3-4a27-ac5c-a1d5608f8f56.m3u8?r=720&v=1&sxl=ja&hash=bd93e581aa874d2e49582d2b8d93e28c68ec2745

<img width="476" alt="11" src="https://user-images.githubusercontent.com/87686356/138548327-dc897ce5-a59f-4990-a30f-42046c69cae8.png">

**Comment by D-LUFFY89** [comment]
HI Essam3152

I can not communicate with you via e-mail, is there a problem?
I am facing the problem of withdrawing the subtitles of a movie from Amazon even though I tried to change the vpn to United States 
https://www.justwatch.com/us/tv-show/snow-animals/season-1
