### ISSUE TITLE
webm mpd format support

### ISSUE THREAD

**Issue by Marvll** [xhlove/XstreamDL-CLI#26]
https://ok6-13.vkuser.net/?expires=1635476421867&srcIp=154.17.6.60&srcAg=CHROME&ms=95.142.206.140&type=4&sig=KLaiZvOWr6E&ct=6&urls=185.226.52.24%3B45.136.21.33&clientType=0&zs=43&id=1041551264421

`_video_VP9_1920x1080_2078.60kbps 下载开始.
_video_VP9_1920x1080_2078.60kbps                                                                                  0.00/0_video_VP9_1920x1080_2078.60kbps ████████████████████████████████████████████████████████████████████████████████ 0.00/0.00MB • 0.00MB/s • 1/1 • 100.00%

ffmpeg version 4.3.2-2021-02-27-full_build-www.gyan.dev Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 10.2.0 (Rev6, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-lzma --enable-libsnappy --enable-zlib --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libdav1d --enable-libzvbi --enable-librav1e --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-libaom --enable-libopenjpeg --enable-libvpx --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-ffnvcodec --enable-nvdec --enable-nvenc --enable-d3d11va --enable-dxva2 --enable-libmfx --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000016c7e70cf80] Format mov,mp4,m4a,3gp,3g2,mj2 detected only with low score of 1, misdetection possible!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000016c7e70cf80] moov atom not found
concat:0000.mp4: Invalid data found when processing input
_audio_OPUS_194.19kbps 下载开始.
_audio_OPUS_194.19kbps                                                                                  0.00/0.00MB • 0.00MB/s • 0/1 • 0.00% Traceback (most recent call last):
  File "XstreamDL_CLI\__main__.py", line 4, in <module>
  File "XstreamDL_CLI\cli.py", line 148, in main
  File "XstreamDL_CLI\daemon.py", line 33, in daemon
  File "XstreamDL_CLI\downloader.py", line 204, in download_streams
  File "asyncio\base_events.py", line 579, in run_until_complete
  File "XstreamDL_CLI\downloader.py", line 314, in do_with_progress
  File "XstreamDL_CLI\downloader.py", line 140, in to_stop
  File "XstreamDL_CLI\downloader.py", line 122, in update_progress
  File "XstreamDL_CLI\downloader.py", line 100, in calc_speed
ZeroDivisionError: float division by zero
[14688] Failed to execute script __main__`

**Comment by Marvll** [comment]
> try with --raw-concat
> 
> and provide --key to decrypt

没有加密

**Comment by xhlove** [comment]
那--raw-concat就行了
