### ISSUE TITLE
XstreamDL-CLI_v1.3.4_fix

### ISSUE THREAD

**Issue by Marvll** [xhlove/XstreamDL-CLI#28]
当我选择 raw-concat时 不会检查m3u8切片是否完整 直接合并

**Comment by xhlove** [comment]
对于每个分段，软件是接收完数据才会写入本地，除非数据传输错误，否则不存在完整性的问题。除此之外，还有一种可能是你的网络变动了导致，可能软件重新接收了数据。

上面的情况中，第一种和软件无关，软件也管不了。第二种情况目前属于bug，后续会修复。

只要没有上面的情况，直接进行合并有什么问题吗？

**Comment by xhlove** [comment]
针对可能出现下载数据异常的地方进行了修复，如果你还是有疑问，请重开此issue并给出具体说明

https://github.com/xhlove/XstreamDL-CLI/commit/057ee7c875a5b5d247844d63e905bc301680be49
