### ISSUE TITLE
Plis help :)

### ISSUE THREAD

**Issue by Amb33r** [xhlove/XstreamDL-CLI#29]
Hi 

I used download and decrypt example:
`python -m XstreamDL_CLI.cli --select --disable-force-close --limit-per-host 100 --key f31203576a323d09d0c305d236a0c793:00fa546ee19f98fc0044237d2ceb820b "https://akamaicdn.hbogo.eu/a9626f47-b065-2a26-43f9-a3094fb7c4d3_hbo/COMP/29223422_hun_comp_d35eda69-a367-4b47-aa0c-a51032d94be2_3400000_v2.ism/manifest"
`
And i have a bug, sorry i'm a beginner:

![image](https://user-images.githubusercontent.com/70627077/141843297-90559c72-067d-459f-8444-4a1c2ea50e0e.png)

Thank you for your answer

**Comment by xhlove** [comment]
use exe version

**Comment by Amb33r** [comment]
to : https://github.com/xhlove/XstreamDL-CLI/releases/download/1.3.6/XstreamDL-CLI_v1.3.6_fix.exe
how to use exe commands, e.g .:
--best-quality 
???

**Comment by xhlove** [comment]
https://github.com/xhlove/XstreamDL-CLI/blob/master/README_ENG.md

> if you use executable version, replace python -m XstreamDL_CLI.cli to xxx.exe

`XstreamDL-CLI_v1.3.6_fix.exe --select --disable-force-close --best-quality --limit-per-host 100 --key f31203576a323d09d0c305d236a0c793:00fa546ee19f98fc0044237d2ceb820b "https://akamaicdn.hbogo.eu/a9626f47-b065-2a26-43f9-a3094fb7c4d3_hbo/COMP/29223422_hun_comp_d35eda69-a367-4b47-aa0c-a51032d94be2_3400000_v2.ism/manifest"`

**Comment by Amb33r** [comment]
`if you use executable version, replace python -m XstreamDL_CLI.cli to xxx.exe`

I don't understand what to do. Excuse me

**Comment by xhlove** [comment]
download that exe, and run command in the cmd (Command Prompt)

![oCam_2021_11_16_22_29_40_309](https://user-images.githubusercontent.com/48152166/142004188-2fc56c21-771a-4e16-adda-8afda22837fc.gif)

**Comment by Amb33r** [comment]
OK done 
![image](https://user-images.githubusercontent.com/70627077/142007688-3e443360-638e-4aea-89bd-63328ecf246f.png)
and 
![image](https://user-images.githubusercontent.com/70627077/142007755-ab178c4e-623c-41ec-9033-e243db9296e8.png)

but why video has no sound? do i have to use mkvtoolnix myself?

**Comment by xhlove** [comment]
because:

- video is video
- audio is audio
- why should video have audio ?
- why should audio have video ?
- they are different file

yes, mux it yourself

**Comment by Amb33r** [comment]
New: 
`XstreamDL-CLI_v1.3.6_fix.exe --select --disable-force-close --best-quality --limit-per-host 100 --key b86b1e6789635407f212185387c9c485:1e722073a3680feff0dc658e9c3339cd "https://akamaicdn.hbogo.eu/84ef5c4d-7960-26f0-5658-a62b21b84ccf_m129499_hbo/COMP/142325171_pol_comp_2e7ef8a5-dc90-4bfc-99ea-f2247ac75e50_3400000_v2.ism/manifest"`

![image](https://user-images.githubusercontent.com/70627077/142012822-4eebfe33-4660-423f-918c-05d0d9f00d8a.png)

Your tool does not give max video bitrate :( 

![image](https://user-images.githubusercontent.com/70627077/142012959-7cdeb50e-45f6-4218-9162-8bb77d69ad0b.png)

and here is a rip from a group of p2p and probably another tool:

![image](https://user-images.githubusercontent.com/70627077/142013128-38d46116-facd-42b4-9196-12c3827cdbbd.png)

**Comment by xhlove** [comment]
![image](https://user-images.githubusercontent.com/48152166/142013474-40a72d37-10db-4b6a-8408-775f267b81cb.png)

Big idiot ? How could I get 5000kpbs from you link which DO NOT contains track?

**Comment by Amb33r** [comment]
I told you that I am learning
please tell me how did you get the max bitrate?
