### ISSUE TITLE
Pipe to ffmpeg for live stream?

### ISSUE THREAD

**Issue by NH-Networks** [xhlove/XstreamDL-CLI#3]
Can it decode mpeg-dash (clearkey) and pipe livestream to ffmpeg?

**Comment by xhlove** [comment]
not support now.

**Comment by NH-Networks** [comment]
The pipe to ffmpeg or mpeg-dash (clearkey)?

**Comment by xhlove** [comment]
Only m3u8 stream is supported now, dash will coming soon...

**Comment by NH-Networks** [comment]
great 👍 thank you, hope it will come soon

**Comment by NH-Networks** [comment]
any update on this ?

**Comment by xhlove** [comment]
can you provide live dash stream url for test ?

**Comment by NH-Networks** [comment]
sure, but can't give it in public

**Comment by NH-Networks** [comment]
Please try this one 

Mpd link:
https://cdxaws-ak.akamaized.net/out/v1/519ad01e459d4014a6a950fc3b20d2f4/0a4241a1284e400793532dde98bd59e2/f89741fa8a32481e98eb32f8731adb36/manifest.mpd
keys:
0201c4f3901c53ed106a42c25a654da (KID=b5f5354661ff41dfa24a514e507c040b)

**Comment by NH-Networks** [comment]
any updates?

**Comment by NH-Networks** [comment]
it's working now but it's only processing one segment and then stops (live stream) 

manifest_video_H264_1280x720_4000.00kbps download start.
manifest_video_H264_1280x720_4000.00kbps -------------------------------- 100.00% • 15.8/15.8 MiB • 32.0 MB/s • 0:00:00
initm4s
0000.m4s
0001.m4s
0002.m4s
0003.m4s
0004.m4s
        1 file(s) copied.
成功合并 D:/temp/HLS/Downloads/manifest_video_H264_1280x720_4000.00kbps.mp4
已删除 D:/temp/HLS/Downloads/manifest_video_H264_1280x720_4000.00kbps
开始解密

**Comment by maniek1994** [comment]
key extractor ??

**Comment by xhlove** [comment]
> it's working now but it's only processing one segment and then stops (live stream)
> 
> manifest_video_H264_1280x720_4000.00kbps download start. manifest_video_H264_1280x720_4000.00kbps -------------------------------- 100.00% • 15.8/15.8 MiB • 32.0 MB/s • 0:00:00 initm4s 0000.m4s 0001.m4s 0002.m4s 0003.m4s 0004.m4s 1 file(s) copied. 成功合并 D:/temp/HLS/Downloads/manifest_video_H264_1280x720_4000.00kbps.mp4 已删除 D:/temp/HLS/Downloads/manifest_video_H264_1280x720_4000.00kbps 开始解密

you can send its link(live stream) to my mail, mail address at my profile page.

**Comment by xhlove** [comment]
If you have new question, open new issue or contact via email, send me detail info with log.
