### ISSUE TITLE
Live stream DASH non-work after the first seg.

### ISSUE THREAD

**Issue by NecomimiSoske** [xhlove/XstreamDL-CLI#30]
![image](https://user-images.githubusercontent.com/94454036/141982548-575abbf6-b9c9-4031-a40f-6ede48b0041a.png)
大老好，打擾了。
直播解析第一次下載成功，第二次開始log有紀錄正常解析，但不下載。

第一次
![image](https://user-images.githubusercontent.com/94454036/141982838-7e792d5a-4e1e-419d-a61d-b1b21b3903b5.png)
第二次以後
![image](https://user-images.githubusercontent.com/94454036/141982878-8eed6469-2830-43a0-ab61-004ed359958c.png)

**Comment by xhlove** [comment]
第一你提供的信息太少，而且仅仅是截图。

第二建议你测试一下1.3.2版本，新版逻辑有变化，有些问题

**Comment by NecomimiSoske** [comment]
使用最新版git
命令行：python -m XstreamDL_CLI.cli --live --key "068a30ca42dbc556b2f80ce18b1cdd12:de4386bf78d1a6f414ae758bbb902f58" "https://smsalive1.akamaized.net/d6ef12f59452405d8bef582752c763c3/ap-northeast-1/6160987583001/playlist.mpd" --best-quality --overwrite --index-to-name --show-init

**Comment by xhlove** [comment]
**第二建议你测试一下1.3.2版本**

**Comment by NecomimiSoske** [comment]
![image](https://user-images.githubusercontent.com/94454036/141986555-b69f6c48-f181-4952-9e4a-4d97c23a9d0a.png)
1.3.2版本只下載一次，變成普通模式下載。

**Comment by xhlove** [comment]
你测试一下新版，应该可以

**Comment by xhlove** [comment]
对于直播，每次下新的之前记得删除之前的临时文件夹

**Comment by xhlove** [comment]
我发现这个地址刷新得比较快，加了一个`--live-refresh-interval`选项，可以避免漏分段

建议设置为1

**Comment by NecomimiSoske** [comment]
可以了!您真的很迅速，謝謝!
