### ISSUE TITLE
删

### ISSUE THREAD

**Issue by chali26** [xhlove/XstreamDL-CLI#31]
。

**Comment by xhlove** [comment]
> only one segment, please download it manually

只有一个分段，请手动下载。

**Comment by chali26** [comment]
那我是要手动输入那个mp4链接 去浏览器里下吗  还是要怎么输入啊 但是这样的链接好像是没解密的

**Comment by xhlove** [comment]
可以使用IDM、aria2等软件下载，再使用mp4decrypt解密。

**Comment by chali26** [comment]
可以了 谢谢
