### ISSUE TITLE
解密下载失败

### ISSUE THREAD

**Issue by Sharon-Lu** [xhlove/XstreamDL-CLI#33]
某酷，通过javascript:prompt(videoPlayer.getData()._videoData.title + " key", btoa(String.fromCharCode.apply(null, new Uint8Array(____hexA))));获取的key，用工具下载：
python -m XstreamDL_CLI.cli --b64key QlljqA5TSyRakTO0Jm40Ng==  --name flow “https://valipl.cp31.ott.cibntv.net/697473B0DA435716915DD2F84/030005000061A586548BB780000000ED0DDDA6-B32E-4EF0-8E6A-947BFFE806BB.m3u8?ccode=0502&duration=3779&expire=18000&psid=0c822403ef688714c092f39117abcb1a43346&ups_client_netip=da00f0a3&ups_ts=1638283396&ups_userid=&utid=jAFVGLMpEHMCATt4dfHl7FbX&vid=XNTIwMDc1NDA3Ng&vkey=B6318a84fc0d17f1edc793d192988125e&sm=1&operate_type=1&dre=u37&si=73&eo=1&dst=1&iv=0&s=bede0554d6564b76bfb1&type=flvhdv3&bc=2&hotvt=1&t=f64370af1229952&cug=1&rid=2000000018C465B593AC2E79E1A809B6552FF53E02000000”

无法解密

**Comment by xhlove** [comment]
不支持优酷
