### ISSUE TITLE
Error message "only one segment, please download it manually"

### ISSUE THREAD

**Issue by Essam23** [xhlove/XstreamDL-CLI#35]
Hi, I'm getting the error message "only one segment, please download it manually" when I try to download using mpd URL, this problem started from this commit, before this commit I could download without any problems.

https://github.com/xhlove/XstreamDL-CLI/commit/fa6fcfcd3d4269465dbf89e0ea76b6210d146119

<img width="678" alt="55" src="https://user-images.githubusercontent.com/87686356/146627574-933f96d8-c2fe-4572-900c-38dbcc6fb628.png">

The mpd link expires very fast, but here is the mpd file

[717575237053-1617969874401-master.zip](https://github.com/xhlove/XstreamDL-CLI/files/7738667/717575237053-1617969874401-master.zip)

and here is the debug log

[XstreamDL-2021-12-18_053151.zip](https://github.com/xhlove/XstreamDL-CLI/files/7738664/XstreamDL-2021-12-18_053151.zip)

I used the master branch.

https://codeload.github.com/xhlove/XstreamDL-CLI/zip/refs/heads/master

**Comment by mzikagate** [comment]
looks like osn :) send series url i can give you direct link for it

**Comment by Essam23** [comment]
@mzikagate Yes, this problem is with OSN, and thank you for your offer, I was looking to get OSN working again with XstreamDL-CLI in the newer versions.

**Comment by Essam23** [comment]
@xhlove Thank you so much for fixing this problem, the downloading works fine now.

**Comment by mzikagate** [comment]
contact me for offer osn complete downloading script 
https://t.me/zika13651
