### ISSUE TITLE
请问下载的临时文件在哪

### ISSUE THREAD

**Issue by 362227** [xhlove/XstreamDL-CLI#37]
我下载的是直播dash流，看这个工具的命令反馈是一边下载直播一边合并dash片段，请问在不暂停直播下载的情况下怎么把合并的临时文件（视频流和音频流）找出来

**Comment by xhlove** [comment]
> 这个工具的命令反馈是一边下载直播一边合并dash片段

错误，工具是持续下载，下载结束后再合并

如果你没有指定`--save-dir`，那么临时下载文件默认在`Downloads`文件夹下

**Comment by 362227** [comment]
好吧。不知道能不能支持实时合并的功能，实时生成视合并好的频流和音频流，

**Comment by xhlove** [comment]
实时合并不太现实，因为每一次合并都要复制一遍完整的文件，这会非常耗时

而且随着下载的分段越来越多，每一轮产生的文件都会更大

如果你想实现你需要的实时合并功能，请自行写其他脚本处理。
