### ISSUE TITLE
下载的只有分段文件不能自动合并

### ISSUE THREAD

**Issue by chan1108** [xhlove/XstreamDL-CLI#41]
是因为视频被加密导致不能合并吗？

**Comment by xhlove** [comment]
你提供的信息太少，无法判断，请阅读README中反馈部分的说明。

**Comment by chan1108** [comment]
> 你提供的信息太少，无法判断，请阅读README中反馈部分的说明。

--best-quality --disable-auto-exit --save-dir "Downloads" --limit-per-host 4 "https://v9-xg-web-default.ixigua.com/56d8fa8f12c434c9c7f40f00f2a1b97c/62120676/dash/tos-cn-v03043g10000c84ukf3c77u5e17no6tg/tos-cn-vd-0026_2b4420adb1b44930a85580a20a02640e_6462af7348a74f2ea3c2897443b44332_8908bdc2159247f989939be28c14fcb8_2a2892f52c5f4f1fbf5f8d87b73f75bc_afe1726f8bc0412fa4239fb9ee211f4d_d6d80f200b2144fc8a4fb989c68cb2ce.mpd?a=1768&br=0&bt=0&cd=1%7C0%7C0%7C0&ch=0&cr=0&cs=&cv=1&dr=0&ds=&er=0&ft=gKJis88-o1rDp7nz7TQ_plXxuhsdK_detqY&l=20220220142155010212097232074F8E8B&lr=default&mime_type=video_mp4&net=0&pl=0&qs=&rc=ajlxNDg6Zml4OzMzNDYzM0ApZ3FsNGJyNDBoMWAtLWQxMHNzOmM%3D&vl=&vr=?"

**Comment by chan1108** [comment]
> > 你提供的信息太少，无法判断，请阅读README中反馈部分的说明。
> 
> --best-quality --disable-auto-exit --save-dir "Downloads" --limit-per-host 4 "https://v9-xg-web-default.ixigua.com/56d8fa8f12c434c9c7f40f00f2a1b97c/62120676/dash/tos-cn-v03043g10000c84ukf3c77u5e17no6tg/tos-cn-vd-0026_2b4420adb1b44930a85580a20a02640e_6462af7348a74f2ea3c2897443b44332_8908bdc2159247f989939be28c14fcb8_2a2892f52c5f4f1fbf5f8d87b73f75bc_afe1726f8bc0412fa4239fb9ee211f4d_d6d80f200b2144fc8a4fb989c68cb2ce.mpd?a=1768&br=0&bt=0&cd=1%7C0%7C0%7C0&ch=0&cr=0&cs=&cv=1&dr=0&ds=&er=0&ft=gKJis88-o1rDp7nz7TQ_plXxuhsdK_detqY&l=20220220142155010212097232074F8E8B&lr=default&mime_type=video_mp4&net=0&pl=0&qs=&rc=ajlxNDg6Zml4OzMzNDYzM0ApZ3FsNGJyNDBoMWAtLWQxMHNzOmM%3D&vl=&vr=?"

这是下载的命令，尝试勾选二进制合并后下载也只有分段文件无法合并

**Comment by xhlove** [comment]
我测试没有问题，请使用最新版CLI，还不行提供下完整日志。二进制合并的命令是`--raw-concat`

![image](https://user-images.githubusercontent.com/48152166/154832188-02b960d2-9b19-4e71-b23b-39946c4b8889.png)

**Comment by chan1108** [comment]
![image](https://user-images.githubusercontent.com/54262303/154832903-a95825b7-fb84-4cc1-8ecd-d72362e2a6a1.png)

![image](https://user-images.githubusercontent.com/54262303/154833498-24a47a75-981b-4057-af05-128699d25a6b.png)

![image](https://user-images.githubusercontent.com/54262303/154833504-d430426a-a2d2-42ab-b9d6-f15ffcd111d5.png)

我这里没显示有merged successfully的那一行

**Comment by chan1108** [comment]
[XstreamDL-2022-02-20_152754.log](https://github.com/xhlove/XstreamDL-CLI/files/8103602/XstreamDL-2022-02-20_152754.log)
这是日志

**Comment by xhlove** [comment]
自动获取得到的文件名太长了。。临时解决方案是手动指定一下文件名
