### ISSUE TITLE
Now E 字幕时间轴

### ISSUE THREAD

**Issue by Marvll** [xhlove/XstreamDL-CLI#42]
![image](https://user-images.githubusercontent.com/88202244/156529066-f1ad6f52-90fc-4e9d-adff-0014ae6c7ec6.png)
这里的时间轴与webvtt不一致，经查看所有时间轴均是如此
![image](https://user-images.githubusercontent.com/88202244/156529127-36e783ad-167e-455c-9f5c-49089af35713.png)

![image](https://user-images.githubusercontent.com/88202244/156530098-615f381c-32f4-498f-8fb9-8251e2da955b.png)

![image](https://user-images.githubusercontent.com/88202244/156530047-1b966bdf-adc3-4189-a75e-f07ded72b6ff.png)

[首集免费](https://www.nowe.com/season/S202107270134707/%E6%88%91%E7%9A%84%E5%A4%A9%E6%89%8D%E5%A5%B3%E5%8F%8B-%E7%AC%AC1%E5%AD%A3)
[manifest_subtitle_vtt_yue_stream_7.zip](https://github.com/xhlove/XstreamDL-CLI/files/8176277/manifest_subtitle_vtt_yue_stream_7.zip)

[manifest.zip](https://github.com/xhlove/XstreamDL-CLI/files/8176338/manifest.zip)

**Comment by xhlove** [comment]
这是一个已知情况，但是我认为不应该是下载器做，你可以单独写个脚本处理。

---

请结合raw.json中链接的`Segment-491650000.vtt`这部分，以及mpd内的timescale参数，自行计算每个vtt文件对应的基准时间，然后修正时间轴，以及合并一些关联的字幕。

基准时间 = 链接末尾的数字 / timescale

例如，你截图第一张最早出现在`0005.vtt`中，链接末尾是`Segment-411650000.vtt`

基准时间就是(411650000 / 10000000)

```
00:00:07.000 --> 00:00:07.999
(你很久沒見她，她情況轉差了)
```

`0006.vtt`则是`Segment-491650000.vtt`

基准时间 (491650000/ 10000000)

```
00:00:00.000 --> 00:00:02.240
(你很久沒見她，她情況轉差了)
```

**Comment by mrbing203** [comment]
我也碰到这种情况，请问下有没有适合脚本呢，没学过编程，不太会代码

**Comment by mrbing203** [comment]
> 这是一个已知的情况，我认为不应该是下载器做的，你可以单独写个脚本处理。
> 
> 结合raw.json中链接这部分，以及内部`Segment-491650000.vtt`的timescale参数，自己计算出每个vtt文件的基准时间，然后，以及相关联的时间的字幕。
> 
> 基准时间 = 链接的价格/时间刻度
> 
> 例如，你的截图第一张在`0005.vtt`中，链接是出现`Segment-411650000.vtt`
> 
> 基准时间就是(411650000 / 10000000)
> 
> ```
> 00:00:07.000 --> 00:00:07.999
> (你很久沒見她，她情況轉差了)
> ```
> 
> `0006.vtt`惯`Segment-491650000.vtt`
> 
> 基准时间 (491650000/ 10000000)
> 
> ```
> 00:00:00.000 --> 00:00:02.240
> (你很久沒見她，她情況轉差了)
> ```

我也碰到这种情况，请问下有没有适合脚本呢，没学过编程，不太会代码

**Comment by Marvll** [comment]
`import os, json, sys, re , copy
#Author: Xiaoqiu2451 QQ:2451437216


def getTimeScale(path: str) -> float:
    with open(os.path.join(path, 'manifest.mpd'), encoding='utf-8') as f:
        mdpFile = f.read()
    timescale = re.search(r'(?<=timescale=\")\d*(?=\")', mdpFile)
    print(f'時間放大基準: {timescale}')
    return float(timescale.group())

def getVTTFileList(path: str, TimeScale: float) -> list[tuple]:
    subtitlePath = os.path.join(path, 'manifest_subtitle_vtt_yue')
    with open(os.path.join(subtitlePath, 'raw.json'), encoding='UTF-8') as f:
        rawjsonInfo = json.load(f)
    VTTFiles = list()
    for vttsubtitle in rawjsonInfo['segments']:
        vttSegmentNum = vttsubtitle['url'].split('/')[-1].split('-')[1].split('.')[0]  #別動就對了
        VTTFiles.append((os.path.join(subtitlePath, vttsubtitle['name']), int(vttSegmentNum) / TimeScale))
        print(f'VTT文件: {vttsubtitle["name"]}, 基準時間:{int(vttSegmentNum) / TimeScale}')
    return VTTFiles

def getTimeStamp(isoform: str) -> float:  #將ISO時間格式轉為時間戳
    stamp = 0.0
    hour, minute, second = map(lambda x: float(x.replace(',', '.')), isoform.split(':'))
    stamp += hour*3600 + minute*60 + second
    return stamp

def readVTTSubtitle(VTTFiles: list):
    subtitles = list()
    for vttFilePath, VTTstartTime in VTTFiles:
        with open(vttFilePath, encoding='UTF-8') as f:
            vttFileLine = map(lambda x: x.strip(), f.readlines())
        tmpTime = ''  #先聲明一下
        tmpSubtitle = ''
        for line in vttFileLine:
            if ' --> ' in line:  #為時間軸
                tmpTime = line
            elif line != '' and tmpTime:  #為字幕
                if tmpSubtitle:
                    tmpSubtitle += '\n' + line
                elif not tmpSubtitle:
                    tmpSubtitle = line
            elif line == '' and tmpTime and tmpSubtitle:
                starttime, endtime = map(getTimeStamp, tmpTime.split(' --> '))
                subtitles.append(copy.copy((starttime + VTTstartTime, endtime + VTTstartTime, tmpSubtitle)))
                tmpTime = ''  #先聲明一下
                tmpSubtitle = ''
    return subtitles

def stampToISOForm(stamp: float) -> str:
    seconds = stamp % 60
    secondInt = str(seconds).split('.')[0].rjust(2, '0')
    secondFloat = str(seconds).split('.')[1].ljust(3, '0')[:3]
    hours = int(stamp // 3600)
    minutes = int(stamp // 60 - hours * 60)
    return str(hours).rjust(2, '0') + ':' + str(minutes).rjust(2, '0') + ':' + secondInt + '.' + secondFloat

def writeVTTFile(subtitles: list, path: str) -> None:
    VTTFilePath = os.path.abspath(os.path.basename(path) + '.vtt')  #以文件名作為最後整合的文件
    VTTFileIO = open(VTTFilePath,'w',encoding='UTF-8')
    VTTFileIO.writelines(('WEBVTT', '\n\n'))  #VTT頭
    while subtitles:  #我們需要干涉下一個的字幕作為對比 於是無法使用for
        starttime, endtime, text = subtitles.pop(0)
        if subtitles and subtitles[0][2] == text:
            if subtitles[0][0] - endtime < 0.01:  #設置偏差值 在偏差值內的在合併
                endtime = subtitles.pop(0)[1]  #這樣只能去除一次重複的 不過應該夠用了
        tmpList = (stampToISOForm(starttime), ' --> ', stampToISOForm(endtime), '\n', text, '\n\n')
        VTTFileIO.writelines(tmpList)
    print(f'已統合完成 文件保存在 {VTTFilePath}')




def inputFolder() -> str:
    #獲取文件夾 如果argv不存在
    path = input('請輸入文件夾鏈接（可以拖入） ')
    if path.startswith('"'):
        path = path[1:-1]  #去除"
    return path

if __name__=='__main__':
    if len(sys.argv) == 1:
        path = inputFolder()
    else:
        path = sys.argv[1]
    assert os.path.exists(os.path.join(path, 'manifest.mpd')) and os.path.exists(os.path.join(path, 'manifest_subtitle_vtt_yue')), "manifest.mpd文件或者manifest_subtitle_vtt_yue文件夾不存在!請檢查您輸入的文件夾是否包含!"
    VTTFiles = getVTTFileList(path, getTimeScale(path))
    subtitles = readVTTSubtitle(VTTFiles)
    writeVTTFile(subtitles, path)
`

**Comment by Marvll** [comment]
参见 https://gist.github.com/Marvll/a8cd2c58c9aea8d31a9563e0fb9c6bac

**Comment by mrbing203** [comment]
> 参见 https://gist.github.com/Marvll/a8cd2c58c9aea8d31a9563e0fb9c6bac

我刚在精研发过。。。
