### ISSUE TITLE
Hi! I have the binary in place but the script can't find it

### ISSUE THREAD

**Issue by jcronan-slcc** [xhlove/XstreamDL-CLI#44]
Hi! When I use Linux, Debian to be exact, The script fail to call the mp4decrypt binary. The binary for Linux is in there. This did not happen in Windows

`08:04:47.172 XstreamDL_CLI/cli.py:162 INFO: use 1.4.1, set URI to ['https://tglmp02.akamaized.net/out/v1/9fd968b813e5405194a4fc3db1baae0e/manifest.mpd']
08:04:47.228 XstreamDL_CLI/daemon.py:78 INFO: refresh link https://tglmp02.akamaized.net/out/v1/9fd968b813e5405194a4fc3db1baae0e/manifest.mpd
  0 total   10  segments   36.00s mlpang2_video_H264_960x540_1800.00kbps
  1 total   10  segments   36.00s mlpang2_video_H264_1280x720_2800.00kbps
  2 total   10  segments   36.00s mlpang2_video_H264_1920x1080_4499.97kbps
  3 total   10  segments   36.01s mlpang2_audio_AAC_und_95.25kbps
08:04:50.255 XstreamDL_CLI/downloader.py:309 INFO: mlpang2_video_H264_1920x1080_4499.97kbps download start.
08:04:50.256 XstreamDL_CLI/downloader.py:453 INFO: 12 tasks start
mlpang2_video_H264_1920x1080_4499.97kbps ██████████████████████████████ 23.76/23.76MB • 69.99MB/s • 12/12 • 100.00%
08:04:50.636 XstreamDL_CLI/downloader.py:459 INFO: tasks end, time used 0.38s
08:04:50.638 XstreamDL_CLI/downloader.py:309 INFO: mlpang2_audio_AAC_und_95.25kbps download start.
08:04:50.640 XstreamDL_CLI/downloader.py:453 INFO: 12 tasks start
mlpang2_audio_AAC_und_95.25kbps ██████████████████████████████ 0.54/0.54MB • 3.43MB/s • 12/12 • 100.00%
08:04:50.798 XstreamDL_CLI/downloader.py:459 INFO: tasks end, time used 0.16s
08:04:53.335 XstreamDL_CLI/downloader.py:309 INFO: mlpang2_video_H264_1920x1080_4499.97kbps download start.
08:04:53.337 XstreamDL_CLI/downloader.py:453 INFO: 1 tasks start
mlpang2_video_H264_1920x1080_4499.97kbps ██████████████████████████████ 25.81/25.81MB • 39.63MB/s • 13/13 • 100.00%
08:04:53.388 XstreamDL_CLI/downloader.py:459 INFO: tasks end, time used 0.05s
08:04:53.390 XstreamDL_CLI/downloader.py:309 INFO: mlpang2_audio_AAC_und_95.25kbps download start.
08:04:53.391 XstreamDL_CLI/downloader.py:453 INFO: 1 tasks start
mlpang2_audio_AAC_und_95.25kbps ██████████████████████████████ 0.59/0.59MB • 2.92MB/s • 13/13 • 100.00%
08:04:53.408 XstreamDL_CLI/downloader.py:459 INFO: tasks end, time used 0.02s
^C08:04:56.474 XstreamDL_CLI/models/stream.py:233 INFO: /root/XstreamDL-CLI/Downloads/mlpang2_video_H264_1920x1080_4499.97kbps.mp4 was merged successfully
start decrypt
sh: 1: /root/XstreamDL-CLI/binaries/mp4decrypt --show-progress --key [redacted] /root/XstreamDL-CLI/Downloads/mlpang2_video_H264_1920x1080_4499.97kbps.mp4 /root/XstreamDL-CLI/Downloads/mlpang2_video_H264_1920x1080_4499.97kbps_decrypted.mp4: not found
08:04:56.480 XstreamDL_CLI/models/stream.py:233 INFO: /root/XstreamDL-CLI/Downloads/mlpang2_audio_AAC_und_95.25kbps.m4a was merged successfully
start decrypt
sh: 1: /root/XstreamDL-CLI/binaries/mp4decrypt --show-progress --key [redacted] /root/XstreamDL-CLI/Downloads/mlpang2_audio_AAC_und_95.25kbps.m4a /root/XstreamDL-CLI/Downloads/mlpang2_audio_AAC_und_95.25kbps_decrypted.m4a: not found`

Is there anything that I need to do? thank you!

**Comment by xhlove** [comment]
please FEEDBACK by RULES

https://github.com/xhlove/XstreamDL-CLI/blob/master/README_ENG.md#feedback
