### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by snowywish** [xhlove/XstreamDL-CLI#45]
Hello,
every time i tried to download the video i keep getting this error
![Screenshot_2](https://user-images.githubusercontent.com/80122897/157093436-fa921a11-0334-48a7-806b-d6c3316b3aa8.jpg)
could please tell me where did i go wrong? i follow ever step but still this

**Comment by xhlove** [comment]
try to run at non-blank path

**Comment by snowywish** [comment]
![Screenshot_2](https://user-images.githubusercontent.com/80122897/157507153-d96f1b19-07d9-41be-9fb7-f408cbc413c1.jpg)

**Comment by xhlove** [comment]
exe is not in the path.

Google "how to use powershell to run exe"
