### ISSUE TITLE
鹅大这是什么问题？

### ISSUE THREAD

**Issue by xiaoxiaoliya** [xhlove/XstreamDL-CLI#48]
D:\Axiaoli\XstreamDL-CLI-master\XstreamDL-CLI-master>py -m XstreamDL_CLI.cli https://ols-ww100-cp.akamaized.net/manifest/master/46bac75a-1c4b-11ec-a25c-023391da732a/65794a72596d6c30496a6f7a4e6a67324e4441774d444173496e42735958526d62334a74496a6f695a47567a6133527663434973496d526c646d6c6a5a565235634755694f694a335a5749694c434a746232526c62434936496e6470626d527664334d694c434a7663315235634755694f694a6a61484a76625755694c434a7663794936496a6b354c6a41754e4467304e434973496d467763434936496a4d754d434a39/dash.mpd?cpatoken=exp=1648226827~acl=/manifest/master/46bac75a-1c4b-11ec-a25c-023391da732a/*~hmac=b4c94d2018ccc040e8fdc6fdf5065f783f1ff40330f73dcfc4c1143ff023cc73&access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkZXZpY2VfaWQiOm51bGwsIndhdGNoX3R5cGUiOiJQUkVNSVVNIiwicHJvZ3JhbV9pZCI6IjViZGFmMzYzLTM0YjItNDA5NS1hZmQ1LTI2MDlkYmMyYjk2OCIsInBhcmVudF9wcm9ncmFtX2lkIjoiZWExMDRkMDItYTZkNC0xMWU5LWJhN2EtMDZkNTQ0MDJkZDBjIiwiY2xpZW50X2lkIjoiNGQ3MDViZTQtYTQ5ZS0xMWVhLWJiMzctMDI0MmFjMTMwMDAyIiwidmlkZW9fdHlwZSI6InZvZCIsImdyYW50X3R5cGUiOiJwbGF5X3ZpZGVvIiwidXNlcl9pZCI6ImU3NDQ5M2E2LWRlOGUtNGI1ZS1hNTM1LTA0N2JhZTMyNTZhYSIsImN1cnJlbnRfc2Vjb25kIjo2ODYsInJlcG9ydF9pZCI6IlhZOTQiLCJzY29wZSI6WyJwdWJsaWM6LioiLCJtZTouKiJdLCJleHAiOjE2NDgzOTk2MjQsImRldGVjdGlvbl9pZCI6bnVsbCwidmlkZW9faWQiOiI0NmIyMWQ3Ni0xYzRiLTExZWMtYTI1Yy0wMjMzOTFkYTczMmEiLCJpc3MiOiJBc2lhcGxheS1PQXV0aC1TZXJ2ZXIiLCJpYXQiOjE2NDgxNDA0MjQsInRlcnJpdG9yeSI6IlRXIn0.lw0xVALOrK-cWhaJY6-x6YNfkeRlCor0EqBmTG1v01s
00:49:03.195 XstreamDL_CLI\cli.py:161 INFO: use 1.4.1, set URI to ['https://ols-ww100-cp.akamaized.net/manifest/master/46bac75a-1c4b-11ec-a25c-023391da732a/65794a72596d6c30496a6f7a4e6a67324e4441774d444173496e42735958526d62334a74496a6f695a47567a6133527663434973496d526c646d6c6a5a565235634755694f694a335a5749694c434a746232526c62434936496e6470626d527664334d694c434a7663315235634755694f694a6a61484a76625755694c434a7663794936496a6b354c6a41754e4467304e434973496d467763434936496a4d754d434a39/dash.mpd?cpatoken=exp=1648226827~acl=/manifest/master/46bac75a-1c4b-11ec-a25c-023391da732a/*~hmac=b4c94d2018ccc040e8fdc6fdf5065f783f1ff40330f73dcfc4c1143ff023cc73']
00:49:04.125 XstreamDL_CLI\extractor.py:104 WARNING: 无法获取视频流信息
'access_token' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

**Comment by xhlove** [comment]
链接部分没有加双引号。。
