### ISSUE TITLE
下载字幕问题

### ISSUE THREAD

**Issue by xiaoxiaoliya** [xhlove/XstreamDL-CLI#50]
鹅大
https://github.com/wayneclub/Subtitle-Downloader 使用这个项目时，字幕没下载完就中断 下载下一个了
日志文件
[XstreamDL-2022-03-31_161451.log](https://github.com/xhlove/XstreamDL-CLI/files/8387420/XstreamDL-2022-03-31_161451.log)
![image](https://user-images.githubusercontent.com/94291982/161010145-8f7c6315-bcea-4beb-91d4-49d27c79543a.png)

**Comment by xhlove** [comment]
![image](https://user-images.githubusercontent.com/48152166/161050455-425bf929-db46-431a-9a23-e6cbe9960239.png)

日志不全，链接没有，不会提问就不要提。
