### ISSUE TITLE
大大 请教一下这个是什么问题？

### ISSUE THREAD

**Issue by daliali2088** [xhlove/XstreamDL-CLI#52]
![image](https://user-images.githubusercontent.com/77323405/164037518-4413a1aa-6c4b-4464-ab4b-353d2f540bea.png)
![image](https://user-images.githubusercontent.com/77323405/164037581-718ed135-98e3-4c2a-a7a6-021b058c402c.png)
可以解析，但是下载会出错
MPD：`https://hses5.hotstar.com/videos/hotstarint/1260082738/1260082740/v3/1645784284423/52c00cab79ea700623db005b11805403/master-72bb5517b8-tv-0.mpd?hdnea=st=1650381117~exp=1650381717~acl=/videos/hotstarint/1260082738/1260082740/v3/1645784284423/52c00cab79ea700623db005b11805403/*~data=ip=6EWBOWup9PdTUpke7wMZVL-userid=eSIfFtHhFFXeY2WV2ltYvMNFRLgJDtEq5CgfgNTsDptl-did=s79yoUngx12MYVhlln9HeI2JVOCgRTZDxHjgdFg6rVAx1BUDew1jspv-cc=th-~hmac=c771ad9d87aa8a082ae51f32ec84007c49c81c8c411942ae0e441c77a24f0198`

heders：
```
{
    "origin": "https://www.hotstar.com",
    "referer": "https://www.hotstar.com/"
}
```

**Comment by daliali2088** [comment]
是的 有时效性 需要泰国ip
MPD:`https://hses5.hotstar.com/videos/hotstarint/1260082738/1260082740/v3/1645784284423/52c00cab79ea700623db005b11805403/master-72bb5517b8-tv-0.mpd?hdnea=st=1650462962~exp=1650463562~acl=/videos/hotstarint/1260082738/1260082740/v3/1645784284423/52c00cab79ea700623db005b11805403/*~data=ip=2nW6azkF2zGsqHXlXJDLPx-userid=eSIfFtHhFFXeY2WV2ltYvMNFRLgJDtEq5CgfgNTsDptl-did=s79yoUngx12MYVhlln9HeI2JVOCgRTZDxHjgdFg6rVAx1BUDew1jspv-cc=th-~hmac=37aa2c0ea2635a4ee4bda7175e7e886271e82a01088e0e502c22da17941de85d`

[manifest.txt](https://github.com/xhlove/XstreamDL-CLI/files/8522112/manifest.txt)

分段链接 是不是这个 `https://hses5.hotstar.com/videos/hotstarint/1260082738/1260082740/v3/1645784284423/52c00cab79ea700623db005b11805403/video_h264_fhd_sdr_1645784284423/avc1/6/init.mp4`

`https://hses5.hotstar.com/videos/hotstarint/1260082738/1260082740/v3/1645784284423/52c00cab79ea700623db005b11805403/audio_aac_1645784284423/ko/mp4a/2/init.mp4`

**Comment by xhlove** [comment]
没有泰国的代理，无法验证，不过通过解析mpd结果来看链接并没有问题，推测你可能用的不是最新版。

另外提供的信息太少，自己检测下cookie问题，headers.json里面的user-agent最好也设置下，不要只设置referer。

试试最新版：

- https://github.com/xhlove/XstreamDL-CLI/actions/runs/2175828153

**Comment by daliali2088** [comment]
我用了新版本好像还是一样的 我试过加user-agent 但是加了之后连解析都解析不出来 但是就保留着两个就可以
