### ISSUE TITLE
能否支持youku copyrightdrm 解密？

### ISSUE THREAD

**Issue by hecoter** [xhlove/XstreamDL-CLI#54]
能否支持youku copyrightdrm 解密
已获取key，希望能支持下载

**Comment by xhlove** [comment]
https://github.com/hecoter/H_m3u8DL/blob/main/H_m3u8DL/Tools/youkudecrypt.exe

**Comment by wansqh** [comment]
https://github.com/hecoter/H_m3u8DL/blob/main/H_m3u8DL/Tools/youkudecrypt.exe 地址失效了
