### ISSUE TITLE
mpd stream match publishTime failed

### ISSUE THREAD

**Issue by cedric8528** [xhlove/XstreamDL-CLI#59]
Hello,

I have tried to download a live mpd stream but I got an error 

![image](https://user-images.githubusercontent.com/114312429/192868185-08787e8e-2570-475c-8693-9e478fc7554f.jpg)

Thank you for your help.

Best regards

Cédric

**Comment by xhlove** [comment]
https://github.com/xhlove/XstreamDL-CLI/actions/runs/3147697507

try with this version

and you can try with https://github.com/nilaoda/N_m3u8DL-RE too

**Comment by cedric8528** [comment]
Thank you xhlove for your quick help.

Don't work with your version ...

![Capture](https://user-images.githubusercontent.com/114312429/193083356-336fc0f2-5960-4bd6-b0f5-ae5eb7a368ee.PNG)

Works with N-m3uDL-RE

![capture5](https://user-images.githubusercontent.com/114312429/193083510-95e2e89f-a2b4-49ca-b87f-bea42fc826bf.PNG)

Best Regards,

Cédric

**Comment by nilaoda** [comment]
@cedric8528 With N-m3u8DL-RE, you need add `--mp4-real-time-decryption` to decrypt segments during record.

**Comment by cedric8528** [comment]
Without this option the stream is decrypted.
I have audio and video separately and I merge them with FFmpeg. :-)

Thank you Nilaoda.

**Comment by xhlove** [comment]
fixed https://github.com/xhlove/XstreamDL-CLI/actions/runs/3158427186

**Comment by cedric8528** [comment]
![Uploading dede.PNG…]()

**Comment by xhlove** [comment]
pip install python-dateutil

**Comment by cedric8528** [comment]
yes as you can see on my screenshot :+1:

**Comment by xhlove** [comment]
exe wont use the package your installed, use the latset version

- https://github.com/xhlove/XstreamDL-CLI/actions/runs/3159136732
